### ISSUE TITLE
scipy missing from dependencies

### ISSUE THREAD

**Issue by chhotii-alex** [ArnaoutLab/diversity#63]
Thus, if you do `pip install` without `scipy` being installed, runtime error.

Do we need the dependency on scipy? Maybe when the scipy API for sparse matrices stabilizes sufficiently, we can point users to a sparse matrix type that quacks so much like an np.ndarray that we don't need to call `issparse`. This is my dream for the future.

**Comment by nhongphuc** [comment]
The pyproject.toml file says dependencies = ["numpy==1.24.0", "pandas>=1.5.2", "ray>=2.2.0"]. If we add "scipy==1.10.0" to this list, would that fix the issue ?

**Comment by chhotii-alex** [comment]
👍
